site_name: Make For Animals 
theme:
  name: material
  palette:
    primary: "white"
    accent: "blue"
  font:
    text: Assistant
features:
    - navigation.tabs
  custom_dir: 'overrides'
  plugins:
  - search
  - optimize
  - projects
  extra_css:
  - https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
