site_name: Make For Animals 
theme:
  name: material
  palette:
    primary: "white"
    accent: #9b111e
features:
    - navigation.tabs
  custom_dir: 'overrides'
plugins:
  - search
  - optimize
extra_css:
  - https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css
  - stylesheets/extra.css
markdown_extensions:
  - admonition
